import React from "react";
import "./About.css";

const About = () => {
  return (
    <>
      <div className="About">
        <div className="About-main">
            <div className="About-section">
               <div className="About-img">

               </div>
               <div className="About-body">

               </div>
            </div>
            <div className="About-section">
                
               <div className="About-body">
                
               </div>
               <div className="About-img">

               </div>
            </div> 
        </div>
      </div>
    </>
  );
};

export default About;
